routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'WebController@index');
Route::get('/contact_us', 'WebController@contactUs');

// auth
Route::view('/loginPage', 'web.loginPage');
// web - 登入
Route::post('/login', 'AuthController@login');
Route::group(['middleware' => 'auth'], function () {
    // web登出
    Route::get('/logout', 'AuthController@logout');
    // 已讀
    Route::post('read-notification', 'WebController@readNotification');
});

// products
Route::group(['prefix' => 'products'], function () {
    Route::post('/check-product', 'ProductController@checkProduct');
    Route::get('/{id}/shared-url', 'ProductController@shareUrl');
    Route::get('/{product_id}', 'ProductController@productDetail');
});



// admin
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['checkAdmin', 'auth']], function () {
    // admin/orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/', 'OrderController@index');
        Route::get('/datatable', 'OrderController@datatable');
        Route::get('/{order_id}', 'OrderController@index');
        Route::get('/excel/export', 'OrderController@export');
        Route::get('{order_id}/excel/export', 'OrderController@export');
        Route::get('/excel/export-by-shipped', 'OrderController@exportByShipped');
    });
    // admin/products
    Route::group(['prefix' => 'products'], function () {
        Route::get('/', 'ProductController@index');
        Route::post('/upload-image', 'ProductController@uploadImage');
        Route::post('/excel/import', 'ProductController@importExcel');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [''];
    public function cartItems(){
        return $this->hasMany(CartItem::class);
    }
    public function orderItems() {
        return $this->hasMany(OrderItem::class);
    }
    public function favorite_users(){
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }
    public function checkQuantity($iQuantity) {
        if ($this->quantity < $iQuantity){
            return false;
        }
        return true;
    }

    public function images() {
        return $this->morphMany(Image::class, 'attachable');
    }

    public function getImageUrlAttribute(){
        $images = $this->images;
        if ($images->isNotEmpty()){
            return Storage::url($images->last()->path);
        }
    }
}

resources/views/web/contact_us.blade.php
@extends('layout.app')
@section('content')
<h3 class="text-center">聯絡我們</h3>
<form action="">
    <div class="form-group mb-3">
        <label for="name" class="form-label">請問你是：</label>
        <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
{{--        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>--}}
    </div>
    <div class="mb-3">
        <label for="date" class="form-label">請問你的消費時間：</label>
        <input type="date" class="form-control" id="name" name="date" aria-describedby="emailHelp">
        {{--        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>--}}
    </div>
    <div class="mb-3">
        <label for="product" class="form-label">你消費的商品種類：</label>
        <select id="product" name="product" class="form-select">
            <option value="物品">物品</option>
            <option value="食物">食物</option>
        </select>
    </div>
    <input type="submit" value="送出">
</form>

@endsection

resources/views/web/index.blade.php
@extends('layout.app')
@section('content')

<div class="row">
    <div class="col">
        <h2 class="text-center">商品列表</h2>
    </div>
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <td>標題</td>
            <td>內容</td>
            <td>單價</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach($products as $product)
            <tr>
                <td><a href="/products/{{$product->id}}">{{$product->title}}</a></td>

                <td>{{$product->content}}</td>
                <td><i class="fa-solid fa-dollar-sign"></i>{{$product->price}}</td>
                <td>
                    <button class="btn btn-primary check_product" type="button" id="{{$product->id}}">
                        <span class="spinner-border spinner-border-sm" id="loading_check_product_{{$product->id}}" role="status" aria-hidden="true" style="display: none"></span>確認商品數量
                    </button>
                </td>
                <td>
                    <button class="btn btn-warning check_shared_url" type="button" id="{{$product->id}}">
                        <span class="spinner-border spinner-border-sm" id="share_product_{{$product->id}}" role="status" aria-hidden="true" style="display: none"></span>
                        分享商品
                    </button>
                </td>
            </tr>
        @endforeach

    </tbody>
</table>
<script>
    $(document).on('click', '.check_product', function () {
        let product = $(this);
        product.attr('disabled', 'disabled');
        let product_id = $(this).attr("id");
        $(`#loading_check_product_${product_id}`).show();
        $.ajax({
            method: 'POST',
            url: '/products/check-product',
            data: {
                'product_id': product_id
            },
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
        }).done(function (res) {
            product.attr('disabled', false);
            $(`#loading_check_product_${product_id}`).hide();
            if (res){
                alert('商品數量充足');
            } else{
                alert('商品數量不夠');
            }
        })
    })

    $(document).on('click', '.check_shared_url', function () {
        let product = $(this);
        product.attr('disabled', 'disabled');
        let product_id = $(this).attr("id");
        $(`#share_product_${product_id}`).show();
        $.ajax({
            method: 'GET',
            url: `products/${product_id}/shared-url`,
        }).done(function (res) {
            product.attr('disabled', false);
            $(`#share_product_${product_id}`).hide();
            alert(`請分享此縮網址：${res.url}`);
        })
    })
</script>
@endsection

resources/views/web/loginPage.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite('resources/sass/app.scss')
    <title>電商網站 - 登入頁面</title>
</head>
<style>
    .border-radius{
        border-radius: 10rem;
    }
</style>
<body class="bg-primary">

<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card my-5">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h3">歡迎回來</h1>
                        <form action="/login" method="post">
                            <div class="mb-1">
                                <label for="exampleInputEmail1" class="form-label"></label>
                                <input type="email" class="form-control border-radius" id="exampleInputEmail1" name="email"
                                       aria-describedby="emailHelp" placeholder="輸入Email">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label "></label>
                                <input type="password" class="form-control border-radius" id="exampleInputPassword1" name="password"
                                       placeholder="密碼">
                                @csrf
                            </div>
                            @if($errors->any())
                                <p class="text-danger text-center">{{$errors->first()}}</p>
                            @endif
                            <button type="submit" class="btn btn-primary btn-block w-100 border-radius">登入</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

resources/views/web/productDetail.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="row gx-5">
            <aside class="col-lg-6">
                <div class="border rounded-4 mb-3 d-flex justify-content-center">
                    <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="{{$product->image_url}}">
                        <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{$product->image_url}}" />
                    </a>
                </div>
                <!-- thumbs-wrap.// -->
                <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-lg-6">
                <div class="ps-lg-3">
                    <h4 class="title text-dark">
                        {{$product->title}}
                    </h4>


                    <div class="mb-3">
                        <span class="h5">NT${{$product->price}}</span>
                        <span class="text-muted">/{{$product->unit_name}}</span>
                    </div>

                    <p>
                        {{$product->content}}
                    </p>

                    <div class="mb-3">
                        <span class="h5">庫存：{{$product->quantity}}</span>
                    </div>

{{--                    <div class="row">--}}
{{--                        <dt class="col-3">Type:</dt>--}}
{{--                        <dd class="col-9">Regular</dd>--}}

{{--                        <dt class="col-3">Color</dt>--}}
{{--                        <dd class="col-9">Brown</dd>--}}

{{--                        <dt class="col-3">Material</dt>--}}
{{--                        <dd class="col-9">Cotton, Jeans</dd>--}}

{{--                        <dt class="col-3">Brand</dt>--}}
{{--                        <dd class="col-9">Reebook</dd>--}}
{{--                    </div>--}}

                    <hr />

                    <div class="row mb-4">
{{--                        <div class="col-md-4 col-6">--}}
{{--                            <label class="mb-2">Size</label>--}}
{{--                            <select class="form-select border border-secondary" style="height: 35px;">--}}
{{--                                <option>Small</option>--}}
{{--                                <option>Medium</option>--}}
{{--                                <option>Large</option>--}}
{{--                            </select>--}}
{{--                        </div>--}}
                        <!-- col.// -->
{{--                        <div class="col-md-4 col-6 mb-3">--}}
{{--                            <label class="mb-2 d-block">Quantity</label>--}}
{{--                            <div class="input-group mb-3" style="width: 170px;">--}}
{{--                                <button class="btn btn-white border border-secondary px-3" type="button" id="button-addon1" data-mdb-ripple-color="dark">--}}
{{--                                    <i class="fas fa-minus"></i>--}}
{{--                                </button>--}}
{{--                                <input type="text" class="form-control text-center border border-secondary" placeholder="14" aria-label="Example text with button addon" aria-describedby="button-addon1" />--}}
{{--                                <button class="btn btn-white border border-secondary px-3" type="button" id="button-addon2" data-mdb-ripple-color="dark">--}}
{{--                                    <i class="fas fa-plus"></i>--}}
{{--                                </button>--}}
{{--                            </div>--}}
{{--                        </div>--}}
                    </div>
{{--                    <a href="#" class="btn btn-warning shadow-0"> Buy now </a>--}}
{{--                    <a href="#" class="btn btn-primary shadow-0"> <i class="me-1 fa fa-shopping-basket"></i> Add to cart </a>--}}
                    <a href="/" class="btn btn-light border border-secondary py-2 icon-hover px-3">  返回 </a>
                </div>
            </main>
        </div>
    </div>
@endsection